### ISSUE TITLE
Automatic Nexus download fails

### ISSUE THREAD

**Issue by Hoeze** [aokellermann/zotero-nexus#3]
Hi, I just tried the pre-release version of this addon but it seems to fail downloading the PDF every time I try it.

For example, try this article:
https://www.sciencedirect.com/science/article/pii/S2666979X22001100

- Nexus says `"Error: PDF not ..."`, `"Try again later"`.
- Zotero fails to download the article even though it is public-access

=> Would it be possible to limit Nexus download on non-free access articles?
=> Why does the Nexus download fail for me always?

**Comment by aokellermann** [comment]
Zotero has a built-in extension for downloading open access literature. Nexus may not provide PDFs for this.

I'll see if I can disable automatic nexus downloads for this, but no promises. Zotero 7 is coming out soon which will make all existing addons incompatible so I don't want to put much work into this addon. 

This addon uses the [STC Hub API](https://standard--template--construct-org.ipns.dweb.link/#/help/stc-hub-api) for PDF access, which has extremely poor replication of mapping DOIs to PDFs, even though the PDFs may be accessible through STC web interface or the chat bot. I've asked about this in telegram and they said that coverage will gradually increase over time.

**Comment by Hoeze** [comment]
I see, thanks a lot @aokellermann!
Good to know that this is a general issue of STC.

Thank you for developing this extension :+1: :smile:

**Comment by huachuman** [comment]
This is a shame. I mean, no offence to the developer because I don't think it's your fault, but this has never worked for me. I've tried it probably over a hundred times now. The telegram bot almost always finds it, but I don't have a single case of the zotero plugin ever working.

**Comment by aokellermann** [comment]
I have escalated this to nexus developer (see the development channel). He gave me a new Iroh-based hub endpoint to try which is much better, but it has been down for a few days now so I can't test it. I will publish a new release as soon as I am able to get this all working reliably.

**Comment by huachuman** [comment]
Hey @aokellermann, any updates on this? Cheers!

**Comment by aokellermann** [comment]
The new iroh endpoint has been extremely unstable so far so I haven't really been able to test it. I have been bothering the developer about it and he said it is expected to be unstable because they are currently working on it. 

I'll check in tomorrow and if it's working I can probably quickly push out a new release.

**Comment by huachuman** [comment]
Ok interesting. Either way no sweat. Can't expect much if their endpoint is unstable.

**Comment by aokellermann** [comment]
Newest beta release should have much better coverage
