### ISSUE TITLE
[JavaScript Error: "ReferenceError: ZoteroPane is not defined"

### ISSUE THREAD

**Issue by huachuman** [aokellermann/zotero-nexus#4]
I'm not having any success with this. I click "Update Nexus  PDF" and nothing happens. The error console reads:

[JavaScript Error: "ReferenceError: ZoteroPane is not defined" {file: "chrome://zotero-nexus/content/nexus.js" line: 20}]

note: the PDFs exist in nexus telegram bot

Zotero version 6.0.27

**Comment by huachuman** [comment]
anyone?

**Comment by aokellermann** [comment]
I think the ReferenceError is unrelated. See https://github.com/aokellermann/zotero-nexus/issues/3#issuecomment-1739243449 for why PDFs fail
