### ISSUE TITLE
Menu item disappeared

### ISSUE THREAD

**Issue by huachuman** [aokellermann/zotero-nexus#6]
I installed the new beta version after uninstalling the old one. Now the menu item is gone. The addon has successfully installed and the settings (i.e. auto-dl) show up in the settings but no menu item on right click.

W11 Z 6.0.36

**Comment by aokellermann** [comment]
This is by design. Nexus files are now downloaded through Zotero's built-in "find available PDF" feature, so no need for additional menu items.

**Comment by huachuman** [comment]
Oh wow interesting. Thanks for the update.
